### ISSUE TITLE
Support to setup http only

### ISSUE THREAD

**Issue by liny01-nbsa** [RogerAirgood/iocage-plugin-privatebin#1]
Thank you for this nice plugin, it works great. However there's a small issue in my setup. I have a network load balancer which terminates all https connections, where I setup all my certificates. and my 443 port is mapped to it. I would like to set a http only service and setup https part of it out side own my FreeNAS box. Is it possible?

**Comment by ConorBeh** [comment]
The reason I setup https by default is because PrivateBin will not function correctly on Google Chrome without it. You can disable https if you'd like by editing /usr/local/etc/lighttpd/lighttpd.conf inside the jail. Replace 

```
$SERVER["socket"] == "0.0.0.0:443" {
  ssl.engine = "enable"
  ssl.pemfile = "/etc/ssl/privatebin.pem"
}
$HTTP["scheme"] == "http" {
    $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
    }
}
$HTTP["host"] =~ "^www\.(.*)" {
url.redirect = ( "^/(.*)" => "https://%1/$1" )
}
```

with

`$SERVER["socket"] == "0.0.0.0:80" `

Also comment out "mod_openssl" in /usr/local/etc/lighttpd/modules.conf

After that, restart lighttpd by running "service lighttpd restart"

This should disable https. Let me know if you have any issues.

**Comment by liny01-nbsa** [comment]
Thank you, @ConorBeh! I will give this a try this weekend.

**Comment by liny01-nbsa** [comment]
Thanks, @ConorBeh, it works great. the configuration had a small issue. I did the change as you suggested, I got the following error when I try to restart lighttpd:

    2020-03-14 11:10:43: (configfile.c.1316) source: /usr/local/etc/lighttpd/lighttpd.conf line: 500 pos: 1 parser failed somehow near here: (EOL) 

And it starts to work when I update it to

    $SERVER["socket"] == "0.0.0.0:80" {}

After the setup it works perfectly! Thank you for creating this nice package!
